### ISSUE TITLE
Does rdioquiz still work?

### ISSUE THREAD

**Issue by jaredsohn** [rdio/rdioquiz#1]
When I run this at http://rdioquiz.ianloic.com/user, it hangs when starting up.  If I run it locally, it hangs and the server shows an Internal Server Error.  The server log can be found below in the following comment.

**Comment by jaredsohn** [comment]
Here's the server-side log when running locally:

http://0.0.0.0:8080/
127.0.0.1:51118 - - [23/Jan/2014 18:47:17] "HTTP/1.1 GET /" - 200 OK
127.0.0.1:51118 - - [23/Jan/2014 18:47:17] "HTTP/1.1 GET /static/rdioquiz.css" - 200 
127.0.0.1:51120 - - [23/Jan/2014 18:47:17] "HTTP/1.1 GET /static/title.png" - 200 127.0.0.1:51121 - - [23/Jan/2014 18:47:17] "HTTP/1.1 GET /static/poweredby.png" - 200 
127.0.0.1:51118 - - [23/Jan/2014 18:47:17] "HTTP/1.1 GET /static/bg.gif" - 200 

127.0.0.1:51119 - - [23/Jan/2014 18:47:17] "HTTP/1.1 GET /static/halo.png" - 200 
Traceback (most recent call last):
  File "/Users/jared/code2/rdioquiz/rdioquiz/web/application.py", line 242, in process
    return self.handle()
  File "/Users/jared/code2/rdioquiz/rdioquiz/web/application.py", line 233, in handle
    return self._delegate(fn, self.fvars, args)
  File "/Users/jared/code2/rdioquiz/rdioquiz/web/application.py", line 415, in _delegate
    return handle_class(cls)
  File "/Users/jared/code2/rdioquiz/rdioquiz/web/application.py", line 390, in handle_class
    return tocall(*args)
  File "main.py", line 220, in GET
    self.rdio.complete_authentication(web.input().get('oauth_verifier'))
  File "/Users/jared/code2/rdioquiz/rdioquiz/rdio.py", line 69, in complete_authentication
    resp, content = client.request(Rdio.ACCESS_TOKEN, "POST")
  File "/Users/jared/code2/rdioquiz/rdioquiz/python-oauth2/oauth2/__init__.py", line 559, in request
    req.sign_request(self.method, self.consumer, self.token)
  File "/Users/jared/code2/rdioquiz/rdioquiz/python-oauth2/oauth2/**init**.py", line 404, in sign_request
    self['oauth_signature'] = signature_method.sign(self, consumer, token)
  File "/Users/jared/code2/rdioquiz/rdioquiz/python-oauth2/oauth2/**init**.py", line 738, in sign
    hashed = hmac.new(key, raw, sha)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hmac.py", line 133, in new
    return HMAC(key, msg, digestmod)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hmac.py", line 72, in **init**
    self.outer.update(key.translate(trans_5C))
TypeError: character mapping must return integer, None or unicode

127.0.0.1:51119 - - [23/Jan/2014 18:47:19] "HTTP/1.1 GET /signin" - 500 Internal Server Error

**Comment by jaredsohn** [comment]
After some investigation the problem is that a value is unexpectedly encoded as unicode.  If you include:

```
    if type(key) is unicode:
        key = key.encode()
```

within python-oauth2/oauth2/**init**.py prior to

```
    hashed = hmac.new(key, raw, sha)
```

it fixes it in a hacky way.
